#!/bin/sh

pkill compton
pkill polybar
pkill sxhkd

sxhkd &
compton --config .config/compton/compton.conf &
polybar example &
nitrogen --restore &
xsetroot -cursor_name left_ptr &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.00
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#585858"
bspc config focused_border_color "#CC00FF"
bspc config urgent_border_color "#B53939"
bspc config presel_border_color "#CC99AA"
bspc config presel_feedback_color "#682AAC"

bspc rule -a "*:lxqt-notificationd" state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a nitrogen state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Android_Studio state=tiled
bspc rule -a zathura state=tiled

# bspc rule -a mpv state=floating
bspc rule -a feh state=pseudo_tiled
bspc rule -a nemo state=pseudo_tiled

bspc rule -a gpick state=pseudo_tiled
